### ISSUE TITLE
Unclear LICENSE

### ISSUE THREAD

**Issue by xhochy** [minrk/backports.shutil_which#1]
The LICENSE file in the repository states that the project is MIT but the setup.py states that the package is PSF licensed. It would be nice to clear this up.

**Comment by minrk** [comment]
Indeed. The original module, being from the Python standard library, is PSF licensed. The backporting bits (setup.py, basically anything original in this repo) would be MIT, but the main license on the actual code is still PSF since it's unmodified from the original. I added a comment to LICENSE to that effect.
